spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jimmywangking/config.git
          username: jimmywangking
          password: Passw0rd2020
          basedir: /Users/aaronwang/Baron/config/basdir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
